---
version: '3.7'
services:
  vaultwarden:
    image: vaultwarden/server
    container_name: vaultwarden
    user: 1000:1000
    ports:
      - 8002:8080
    volumes:
      - ./vw-data/:/data/
    restart: on-failure
    environment:
      - ROCKET_PORT=8080

  vaultwarden-backup:
    container_name: vaultwarden-backup
    build: .
    #user: 1000:1000
    restart: always
    init: true
    depends_on:
      - vaultwarden
    volumes:
      - ./vw-data:/data/
      - ./test:/backup
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - BACKUP_ADD_DATABASE=true
      - BACKUP_ADD_ATTACHMENTS=true
      - BACKUP_ADD_CONFIG_JSON=true
      #- DELETE_AFTER=1
      - TIMESTAMP=true
      - CRON_TIME=*/1 * * * *
      - TZ=Europe/Berlin
      - UID=1000
      - GID=1000
      - BACKUP_DIR=/backup
      #- BACKUP_DIR_PERMISSIONS=777
      #- BACKUP_DIR_PERMISSIONS=-1
      #- LOG_DIR_PERMISSIONS=-1
      - LOG_DIR=/backup/logs
      - LOG_LEVEL=INFO
      - LOG_CLEAR_AT_START=true
      - BACKUP_ON_STARTUP=true
      #- ENCRYPTION_PASSWORD=testtest
      #- ENCRYPTION_BASE64_GPG_KEY="LS0tLS1CRUdJTiBQR1AgUFVCTElDIEtFWSBCTE9DSy0tLS0tCgptUUlOQkdQeEJ4QUJFQUM4M0lKdW5yZllaSUZROGNtYS9VVWQ0blF3VjdtZUxsSXhSbFN5cVJRaW9vbGZuUXUvCjZoMTYvcGErVkRYSERFMXhFL014SGRjSGFPZTdMNXc4L1F0Z094ZXhpUlF4MklOcVhnWUdjeThjY3M0UjhMaEYKZENlZmsveWhMN2x4dEFYcTVwWHZabVY4QlA1SE5ESFRUMUExZEw4T0ZodVpLWnk2QisrNGFEZ2o1TzFhUlY5bwpDOGhjVWJVOTRXNHQ1YlBVbFVsMmNMSTU0am1wUWF3eFBTWHkwZGIzOE5PSXN3bG9zOWh4TTQ4SUFBM09MS09xCjBDYVUrV2EvRC9ydUNtSkl4a3pObTc5NFJudGdsTkFmZHVRK3djdVFRMCtSWE1ZWVIvQTk4cUNJVi8vU3hXMWQKd0dadW5kaXJUcXZLdTNSZkJzNFluSHV6MjlWOEVUb0pKR3M2cXBSM29OL1FnbEhKMVZydDhxNHhXQ0l3NUtSSQo5UExneTFaTjZBd2tCYXVrRlExNjdLVnQ5TmY2elJEeG9ZUnN3dXREdkthQVJRdUNuRU1ucXp2WWorRnI5WjdHCjQ3YytIb3hVcGhGblRxOC8xWVd1T3VnMkpua2FOOXNtVTEwK3U0eDNMejVwRnU0MmNlVC9sRUZqeDJyYno4dmQKZG1NemZtc1lQVUcrQkNlbUdualhEelo5MVZtUTkvcnhXMjFNYWZBa2hoM2VUaTB3cEIwelNnOXVFUDVpazV1SgpONXpSeDIzTHlUYzV1N3QzTEx5VGxVZHNBUElUQWhoWDdGa2g1MGxKeHJDcURaNkduaXRva1ZXZjJZOWlobnpCCjdXQ25JMUVacGV5YnFVRjZSVlNPWjB2eXJrclBKazNLaGo0aVJRdzBZbXgyZkxURDFHdlVUL1Y0SVFBUkFRQUIKdENaVVpYTjBJRlZ6WlhJZ0tFNXZJRU52YlcxbGJuUXBJRHgwWlhOMFFIUmxjM1F1WTI5dFBva0NUZ1FUQVFvQQpPQlloQkYvenVNMGVSSEJCNVlUS1lxK05qMENVR3Bvc0JRSmo4UWNRQWhzREJRc0pDQWNDQmhVS0NRZ0xBZ1FXCkFnTUJBaDRCQWhlQUFBb0pFSytOajBDVUdwb3NvellQL1JMUG5YRmk5U3RzWVJ5K1RuVEZmM1ZoNDNvZlV2YUUKa0l5ekFHL3JTaEFQdnVUR0tHRmtyaEFtNHJYWGFtUFdiL0o2N01kRWQrN0ErMklLcWV1NVNUK3d3a2x2RmpiZAp1RHREeFEwSmVOM2Q4RlFRdlFTSWhBemMxUVozWTh6VW1aSlI5WnFoaGJvWkl1MDhDUHZlK1oyYWhaL2JHdHBNCkZ1ZEVZbFA5ZG1wSFJDT3pxQ01Ia1BoOFc2MkJWUEt3K29rYTZQRUU4dXBpamh1dmV3M3NxSURISHhpQVVBZmsKZDZsUDJYSEVuWU1FcG9aa3V1Wk9GK0FzMjR6NnAzZ0Y3TzA0dzNlaXJMeVpDNDlmcTNJZlNaMGtiOHFLdTZnNwpqTEhLQ2xNcmh6S1NkVTR4S3NjSG9mRllHSXM4Ny9YRzdtdjJCbmpnTGlhNTNkVUs4UWhmUktUbW9nYTRYdmlsCjYzRWhVSVp0QXR4Vzcxd2hOT3FZa20wR0RSRTVhNlRnK29TbWpHYnNJL2NUWGZIdHRNMitJLy9udzRYOVQ4SVEKeGllK1VOQWROb25GSk43M2t4dWEvUi9HamhFY1pVRUlvdDNNa2trTGE5M0VOSUpFaXNBMlQ5dmJMc2ttNlpyQgpmZ3VXei9XZUwxaURYdU5LbU9LMkdaMG1rQWxOaHVQc1BDUi84V0pjSzVhRFJYVkMxcytFaHU0NVVQZVFrc3d4CklSSzE0cTRtRldDWHpNa1JGeXNxY2hORFo1RjVDWVZJa0J2d0NDMmZ2M3E2a05RVUVUN2JZN3hrNDdzL05HUW0KVlQzcTJzM3NzOC9ESWpJOUd4RCs3aHZmMC9PNXA5eUpTZ1pWRnAvc2tNNmh2STgwaHExRlBQWnZMVVR0OWMyegpCQkZNekRvYVhvSGx1UUlOQkdQeEJ4QUJFQUMvbVNvaTlTNU53R3F0Q211NjdmbWo3WHc5c2ZOWFphclplS0dJCm1LTkhaSFNTdU04NWxEOFhTQ2JNa2RTN2ZyRUZOa2hUa0ZoNXREZEJhTGE5KzFMR1IzZnNZdFpMSDdQOWUvaFQKUjVwUHY4OEpIeFJ0elFZVTNYMmY2Z1piNlBpWExPTTdBc2Z2VlR4Y0l0eEk2K0ZBT08vWXhuTWJxL0tYNnhIYQp4U2x3aTZXM3c4M205UkFUVFQxUWppOU5XcEdZRWtuTkhFK2UzL1F2SWFhRUx5dmY0R3NaUndZMzB1ZDBxM2VGCk5pNENORCtjZXJIOUc4ZWNZaHM0aVV6d29LdWtuUXBOdlc5eGdrZmRKdEZxSm5ITEphNVprYnQvQVRKdmVPQ3UKaG1mdDAxVHcrMXlaSCtFNXdXN2EvbnBoUnV1aXJEWHRaUCswYVdCQ1Y5SUluMHI3SG56eEhhTkEzSEZFNDNvcwpxNzVaaVZXemZMTnQvdWhjSGJocWJmWGdwMDZKUUxxQ0g1dGp1QnJISjZlRlFsZ2FWZ2IrWXc2WUZWZTBQK0JRCjZnWnhpblU5OTkzK2JBN2NzTmZNY2s4eU00OWVib3lHUVh0cmZJTDkxdjNOVDhVOCttQVRDZXEzVWVtQlNIUWwKVTBieHJGTkFrdnc2VnQ3NjBCQlhCOTRDQ3VYVkY4bmM0M2ZKaVN4ZGp5M0hKdVIxVTJTYU1wZEZ5aFlFVkNWSApIUk9uOVJxd1B5c1B6T2oxbWFETko3a2J5SnFDL1ZsZEt3YUFuM2ZDKy9IMnZIdzBmQzRVOG42Y1MyVzllM3kyCjVORTlwcEtINXc5bU9ITEsydUV2anJoZFA4L3hXUFJNcm81YlE4L2RCSWIwT0crYVVuRzVUNlBVTmFTa2djNU8KV0luQ093QVJBUUFCaVFJMkJCZ0JDZ0FnRmlFRVgvTzR6UjVFY0VIbGhNcGlyNDJQUUpRYW1pd0ZBbVB4QnhBQwpHd3dBQ2drUXI0MlBRSlFhbWl3aERRLzlHaEw0M3huQlI1bHRyaE1DcDlYOXU5ZkRpQ1ZDWXk1TGFibDdmQ0FQCjgxNjNhWWtrc1U0NFpjeGs2ZHNFU1dUdXM1M2MzY0x4c3VNU0ZIazVqR000K0RBRzBiWnVnMDRPdkp2R2pWUE8Kc2p4YzFRRllPMFJRdW9PeThSU2VYRmpmK2FhdWc3N2Y2S3BOc1EvSGpQbEtiVktsTTdZcHdaaU5xY3l1WEtzagpaNTNnc05qN292Snl5RFdIVU9ISzZWWXdWVFdMeFQ2bjdNa2tWdHRjcVNjaTFqYlZZVjBQVnc3bEhzMlVITis4CmNkM2tnNm9RYXF5Y1RRRmp4KzQ5NWkrNnRpTVJtTTJRMHozVkJIU0FJKzVuUEc5Tzh3T3FBeVBRUk9nMmV3dGgKdWl4WmJUcTh1dHhpTWFTU1VuK211VlVhSWlvQ0thSUxPUjlIay91d1U5NUZtMVF2c3EvVFJ5OTJlSElsZEt5SAowcDc5YUtjRnFkbHA2T0pXN2x1eDI5YUhiMDhSVGpNT0pWM2xNdjVQTG9lK1NaTTM5a3QzMUJCcDlsaEdnVFJyCkxmOHJjOFczcFh4V0ZyUnNubm5XVXJrSnJKYWswK3plaWRxc2N5clZNb3l4UElRWHZZODFxRjNXYTdvR2x5eEIKVjZXREFTWlJYaVNJU0JPWnVMZlJSUWxseTc2M2oyQmFvNWJPeEZXdlNFZVdCUUhRQzFOOEFtNG9UVzE1Vmhvdwp6SS8yeVFPZEtMSzVSSlRwaFgrbjkyelovb25DUjVTMmRHYklvWno2YUJLYnp1QUdMdWUxTUo4YTIwRUgwZmlsCkowYzYvMlZwcmZBRGdUV2ZGRExNN0psU2xKVzNpYjlOVU5CSzAySnJnYzlOc1NiRUxWamUvcldVekhSeUVSQTUKbUZvPQo9ZUhDdwotLS0tLUVORCBQR1AgUFVCTElDIEtFWSBCTE9DSy0tLS0tCg=="
