version: '3'

services:
  bitwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      - WEBSOCKET_ENABLED=true
    volumes:
      - /volume1/docker/vaultwarden:/data
    ports:
      - 8086:80
      - 3012:3012
  
  vw_backup:
    #image: registry.gitlab.com/1o/vaultwarden-backup:dev
    build: .
    container_name: vaultwarden_backup
    restart: unless-stopped
    init: true
    volumes:
      - /volume1/docker/vaultwarden:/data
      - /volume1/docker/vaultwarden_backup/backups:/backups
      - /volume1/docker/vaultwarden_backup/logs:/logs
    environment:
      - BACKUP_DIR=/backups
      - LOG_DIR=/logs
      - CRON_TIME=0 02,14 * * *
      - TZ=Europe/Berlin
      - DELETE_AFTER=30
      - TIMESTAMP=true
      - UID=1035
      - GID=100
      - BACKUP_ADD_DATABASE=true
      - BACKUP_ADD_ATTACHMENTS=true
      - BACKUP_ADD_CONFIG_JSON=true
      - BACKUP_ADD_RSA_KEY=true
      - BACKUP_ADD_SENDS=true
      - LOG_LEVEL=DEBUG
    # healthcheck:
    #   test: ["CMD", "sh", "/opt/scripts/healthcheck.sh"]
    #   timeout: 2s
    #   retries: 20
